version: "3.8"
services:
  api:
    build:
      context: ./api # Ensure this path points to the directory containing your Dockerfile
      dockerfile: Dockerfile # Specify the Dockerfile if it's not in the root directory
    ports:
      - "5286:5286" # Map host port 5286 to container port 5286
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
